name: Build and push Docker image
run-name: 'Building Docker image by ${{ github.actor }}: ${{ github.event_name }} on ${{ github.ref }}'

on:
  push:
    tags: '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref }} ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fe-project:latest
